sudo: false
language: java
jdk:
   - openjdk11
cache:
  directories:
  - $HOME/.m2  

install:
  - mvn --file ikasaneip/pom.xml --settings .travis.settings.xml test -Dmaven.javadoc.skip=true -Djava.security.egd=file:/dev/./urandom -Pall -B -V

## Build and release to maven central
script:
##  mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
  - if [[ $TRAVIS_BRANCH == "feature/3.1.x-IKASAN-1758-travis-ci-deployment" ]]; then  mvn --file ikasaneip/pom.xml  clean deploy -DskipTests -Dmaven.javadoc.skip=true -Djava.security.egd=file:/dev/./urandom -Pall -B  -V --settings --settings .travis.settings.xml; fi


